[package]
name = "flamer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "net", "sync"] }
axum = "0.8.9"
flame-macro = "0.1.0"
serde="1.0"


[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
opt-level = 3
lto = "thin"
strip = true
codegen-units = 1